package tgb.cryptoexchange.commons.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Merchant {
    ALFA_TEAM("AlfaTeam"),
    ALFA_TEAM_WT("AlfaTeam WT"),
    ALFA_TEAM_QR("AlfaTeam QR"),
    ONLY_PAYS("OnlyPays"),
    EVO_PAY("EvoPay"),
    HONEY_MONEY("HoneyMoney"),
    CROCO_PAY("CrocoPay"),
    BIT_ZONE("BitZone"),
    ONYX_PAY("OnyxPay"),
    EXTASY_PAY("ExtasyPay"),
    EXTASY_PAY_RECEIPT("ExtasyPay Receipt"),
    EXTASY_PAY_RECEIPT_3("ExtasyPay Receipt 3+"),
    EXTASY_PAY_QR("ExtasyPay QR"),
    PAY_LEE("PayLee"),
    PAYSCROW("Payscrow"),
    PAYSCROW_HIGH_CHECK("Payscrow High Check"),
    PAYSCROW_WHITE_TRIANGLE("Payscrow WT"),
    PAYSCROW_SIM("Payscrow SIM"),
    GEO_TRANSFER("GeoTransfer"),
    ROSTRAST("Rostrast"),
    STORM_TRADE("StormTrade"),
    STORM_TRADE_13("StormTrade 13"),
    SETTLE_X("SettleX"),
    SETTLE_X_15("SettleX 15"),
    PLATA_PAYMENT("Plata Payment"),
    PLATA_18("Plata 18"),
    PAY_LEE_QR("PayLee QR"),
    YOLO("Yolo"),
    YOLO_SIM("Yolo sim"),
    NOROS("Noros"),
    NOROS_HIGH_CHECK("Noros High Check"),
    FIAT_CUT("FiatCut"),
    CASH_OUT("Cash Out"),
    PW_PAY("PWPay"),
    GOAT_X("GOATX"),
    GOAT_X_SIM("GOATX Sim"),
    LOTRIEN("Lotrien"),
    GAMBIT("Gambit"),
    GAMBIT_SIM("Gambit Sim"),
    ASGARD("Asgard"),
    ASGARD_WT("Asgard WT"),
    ASGARD_SIM("Asgard Sim"),
    ASGARD_HIGH_CHECK("Asgard High Check"),
    DEORA("Deora"),
    DEORA_SIM("Deora Sim"),
    DEORA_LOW_CHECK("Deora Low Check"),
    DEORA_PDF("Deora PDF"),
    MERIDIAN_PAY("MeridianPay"),
    MERIDIAN_PAY_HIGH_CHECK("MeridianPay High Check"),
    MERIDIAN_PAY_LOW_CHECK("MeridianPay Low Check"),
    MERIDIAN_PAY_SIM("MeridianPay Sim"),
    MERIDIAN_PAY_NSPK("MeridianPay Nspk"),
    SOUZ("Souz"),
    SOUZ_SBP_QR("Souz SBP QR"),
    SOUZ_SIM("Souz SIM"),
    SOUZ_PDF("Souz PDF"),
    BASE_51("Base 51"),
    BASE_51_SIM("Base 51 SIM"),
    BASE_51_LOW_CHECK("Base 51 Low Check"),
    BASE_51_HIGH_CHECK("Base 51 High Check"),
    PRISMA_PAY("Prisma Pay"),
    BUCKS_PAY("Bucks Pay"),
    BUCKS_PAY_SIM("Bucks Pay Sim"),
    MANY_PAY("Many Pay"),
    MANY_PAY_HIGH_CHECK("Many Pay High Check"),
    MANY_PAY_LOW_CHECK("Many Pay Low Check"),
    PAYSYNC("PaySync"),
    CUBE("Cube"),
    CUBE_LOW_CHECK("Cube Low Check"),
    CUBE_HIGH_CHECK("Cube High Check"),
    CUBE_SIM("Cube Sim"),
    RS_PAY("RSPay"),
    RS_PAY_BT("RSPay BT")
    ;

    private final String displayName;
}
